type Query {
    branches(
        pagination: Pagination
        search: String
        sort: Sort
    ): [Branch!]!
    branch(branchId: ID!): Branch
}

type Mutation {
    register(
        branchId: Int!
        staffName: String!
        password: String!
        birthDate: String!
        gender: String!
    ): MutationResponse!



    addBranch(
        branchName: String!
        address: String!
    ): MutationResponse!


    changeBranch(
        branchId: ID!
        branchName: String
        address: String
    ): MutationResponse!

    deleteBranch(branchId: ID!): MutationResponse!
}

type Branch {
    branchId: ID!
    branchName: String!
    branchAddress: String!
    time: String!
}