type Query {
    staffs(
        pagination: Pagination
        search: String
        sort: Sort
    ): [Staff!]!
    staff(staffId: ID!): Staff


#########################################


    allStaffPermission(
        pagination: Pagination
        search: String
        sort: Sort
    ): [Permission!]!
    
}

type Mutation {
    register(
        branchId: Int!
        staffName: String!
        password: String!
        birthDate: String!
        gender: String!
    ): MutationResponse!



    login(
        staffName: String!
        password: String!
    ): MutationResponse!


    updatePermissionStaff(
        staffId: ID!
        create: String
        read: String
        update: String
        deleted: String
    ): MutationResponse!

    # deleteUser(userId: ID!): MutationResponse!
}

type Staff {
    staffId: ID!
    staffName: String!
    branch: String!
    birthDate: String!
    gender: String!
    time: String!
}

type Permission {
    staffId: ID!
    staffName: String!
    branch: String!
    birthDate: String!
    gender: String!
    time: String!
}